services:
  cli:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    working_dir: /workspaces/laygo
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    environment:
      - PYTHONPATH=/workspaces/laygo
      - UV_CACHE_DIR=/workspaces/laygo/.uv-cache
      - TERM=xterm-256color
    
# Optional: Add other services for development

#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379"
